### ISSUE TITLE
Peer disconnected with requested blocks

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit-js-sdk#174] opened 2020-03-26 03:51 UTC
## Problem

When calling the SDK `comitClient.retrieveSwapById()` function, sometimes I come across this issue:

```
[warning] (net) Peer disconnected with requested blocks.
[warning] (net) Resending sync...
[warning] (net) Peer disconnected with requested blocks.
[warning] (net) Resending sync...
[warning] (net) Peer disconnected with requested blocks.
[warning] (net) Resending sync...
```

Executing any swap operations when in this state usually results in:

```
(node:78817) UnhandledPromiseRejectionWarning: Error: Transaction with the same hash was already imported.
    at getResult (/Users/yos/work/comit-app/maker/node_modules/ethers/providers/json-rpc-provider.js:40:21)
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/yos/work/comit-app/maker/node_modules/ethers/utils/web.js:111:30)
    at exports.XMLHttpRequest.dispatchEvent (/Users/yos/work/comit-app/maker/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/yos/work/comit-app/maker/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/yos/work/comit-app/maker/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This halts the entire swap as no further transactions are accepted. Only restarting `comit-scripts` appears to resolve this issue. Has the team encountered this before?

https://github.com/comit-network/app/issues/14

## Goal

Reach out to Yos and fix it.

**Comment by bonomat** [comment] 2020-03-27 00:13
Hi @yosriady : do you think one problem is related to the other or are these two separate issues?

**Comment by thomaseizinger** [comment] 2020-03-27 00:48
> When calling the SDK comitClient.retrieveSwapById() function, sometimes I come across this issue:

Under which circumstances are you calling this function? This is only a workaround for your currently fairly primitive negotiation protocol in the SDK. You should be using the url that is returned from creating a swap at all times, or even better, only interact with the `Swap` class :)

That being said, this call only makes HTTP requests and does not interact with the blockchain nodes. 

The warnings we are seeing here are from bcoin and I suspect their source to be something different :)

**Comment by yosriady** [comment] 2020-03-27 02:22
> Hi @yosriady : do you think one problem is related to the other or are these two separate issues?

@bonomat I believe they are related.



> > When calling the SDK comitClient.retrieveSwapById() function, sometimes I come across this issue:
> 
> Under which circumstances are you calling this function? This function is only a workaround for your currently fairly primitive negotiation protocol in the SDK. You should be using the url that is returned from creating a swap at all times, or even better, only interact with the `Swap` class :)
> 
> That being said, this call only makes HTTP requests and does not interact with the blockchain nodes.
> 
> The warnings we are seeing here are from bcoin and I suspect their source to be something different :)

@thomaseizinger  I'm calling `retrieveSwapById` to get the current swap in order to view the current status and execute the next step in the swap process.

Where can I clarify what the canonical method of retrieving a swap is?

**Comment by yosriady** [comment] 2020-03-27 02:31
Yes, it is possible that it's not `comitClient.retrieveSwapById()` that triggers the errors, but the second error appears to surface because of the first.

**Comment by yosriady** [comment] 2020-04-09 01:24
I'll keep an eye out for the next time this issue happens and export the Parity logs.

**Comment by bonomat** [comment] 2020-04-09 01:26
The first part is bitcoin related and it was caused by bcoin. This will go away with #177 where we get rid of the library

The second part is ethereum related: it seems to be an issue where somehow a transaction is sent to the blockchain twice. 
Yos will provide some more logs once this happens again so that we can investigate it better. 

--> Moving this ticket back to `To Groom` as there is no action right now.

**Comment by yosriady** [comment] 2020-04-09 01:58
@bonomat 

Attached is the logs. The `[warning] (net) Peer disconnected with requested blocks. [warning] (net) Resending sync...` error started at around 01:51:00 onwards.

[parity.log](https://github.com/comit-network/comit-js-sdk/files/4453599/parity.log)

<details>
  <summary>Environment details</summary>

BITCOIN_HD_KEY_0=tprv8ZgxMBicQKsPeecE9RFZyrzwtgvX1TgjCYmxUpWeg96m8orPh3aVioQs2bFPPijyuDxnQFwy6ozcY6XyHb68ShBVka1AmTW5vJVETW1ou6L
BITCOIN_HD_KEY_1=tprv8ZgxMBicQKsPcxrGXzWS1BTG4Bgw7RYLLGGAN8PviWGqxgh8b6Rpw4ia4bHF2DFZFAk85VYN9JUvd925qFQfSCgy6Zram3Q9UGG4uqjvZQo
BITCOIN_P2P_URI=127.0.0.1:57397
ERC20_CONTRACT_ADDRESS=0x62d69f6867a0a084c6d313943dc22023bc263691
ETHEREUM_KEY_0=6fcc868728ab15e9bfbd76b00660fceaa609712886b01a9a49150b51986c750d
ETHEREUM_KEY_1=74d564b8e71c683fe3281deb53c0db6368877adfbfac6fb1e409be3426848d5f
ETHEREUM_NODE_HTTP_URL=http://127.0.0.1:57360
HTTP_URL_CND_0=http://127.0.0.1:57403
HTTP_URL_CND_1=http://127.0.0.1:57404

</details>

**Comment by yosriady** [comment] 2020-04-09 02:47
Here's another set of logs. 

Error surfaces around 02:42:00 onwards.

[parity.log](https://github.com/comit-network/comit-js-sdk/files/4453762/parity.log)

**Comment by bonomat** [comment] 2020-04-09 06:46
@yosriady 
regarding the first message: I assume you wanted to upload the bitcoin log? 
I don't see anything about `[warning] (net) Peer disconnected with requested blocks. [warning] (net) Resending sync..` in there.

Regarding the parity.log: 
I see a few errors in there: 

```
2020-04-09 02:43:54 UTC jsonrpc-eventloop-1 TRACE rpc  Request: {"method":"eth_call","params":[{"to":"0x62d69f6867A0A084C6d313943dC22023Bc263691","data":"0x313ce567"},"latest"],"id":45,"jsonrpc":"2.0"}.
2020-04-09 02:43:55 UTC jsonrpc-eventloop-1 DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x"},"id":45}.
```

Are you doing anything else than swapping on this parity node? I wouldn't know where we are calling a contract with this kind of input and how this is related to our swaps ... It could be the `transfer function` but it looks weird.

If it is though, could it be that we don't provide enough gas? 
For trying this out, can you try to not follow what cnd proposes and just overspend?

**Comment by yosriady** [comment] 2020-04-20 04:39
> @yosriady
> regarding the first message: I assume you wanted to upload the bitcoin log?
> I don't see anything about `[warning] (net) Peer disconnected with requested blocks. [warning] (net) Resending sync..` in there.

Ack, sorry about that. I'll try again and upload the bitcoin.log.

> Regarding the parity.log:
> I see a few errors in there:
> 
> ```
> 2020-04-09 02:43:54 UTC jsonrpc-eventloop-1 TRACE rpc  Request: {"method":"eth_call","params":[{"to":"0x62d69f6867A0A084C6d313943dC22023Bc263691","data":"0x313ce567"},"latest"],"id":45,"jsonrpc":"2.0"}.
> 2020-04-09 02:43:55 UTC jsonrpc-eventloop-1 DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x"},"id":45}.
> ```
> 
> Are you doing anything else than swapping on this parity node? I wouldn't know where we are calling a contract with this kind of input and how this is related to our swaps ... It could be the `transfer function` but it looks weird.
> 
> If it is though, could it be that we don't provide enough gas?
> For trying this out, can you try to not follow what cnd proposes and just overspend?

No, I'm not doing anything else other than swapping on the parity node.

**Comment by bonomat** [comment] 2020-04-20 23:42
> No, I'm not doing anything else other than swapping on the parity node.

Then I assume it's the transfer function. If it is reproducible, can you try this:

> Could it be that we don't provide enough gas?
> For trying this out, can you try to not follow what cnd proposes and just overspend?

**Comment by bonomat** [comment] 2020-05-12 07:32
Closing this until it re-appears again :)

**Closed by bonomat** 2020-05-12 07:32 UTC
Labels: 🐛 bug, 👬 pair-programming
