### ISSUE TITLE
Bitcoin shows incorrect balances

### ISSUE THREAD

**Issue by yosriady** [comit-network/comit-js-sdk#177] opened 2020-03-26 04:17 UTC
# Problem 
When retrieving the maker & taker bitcoin balances from the SDK, it appears to not return the correct balance.

Before a 10 DAI -> 1 BTC Swap:

```
Maker: 100 DAI, 10 BTC
Taker: 100 DAI, 10 BTC
```

After a 10 DAI -> 1 BTC Swap:

```
Maker: 110 DAI, 10 BTC
Taker: 90 DAI, 10 BTC
```

# Goal

Have up2date and correct wallet balances. 

## Proposed Solution

In the `getBalance` method we should check if wallet and chain (bcoin `chain` object) are on the same hight. If not then we have to wait for syncing.

Alternatively we could return the blockhight additionally to the balance. Then the user would have to tackle it in the solution.

**Comment by bonomat** [comment] 2020-03-29 22:10
@yosriady : I moved this issue to the sdk as it is a but there.

**Comment by luckysori** [comment] 2020-04-06 01:10
Spent some time looking into this, here are some notes:

### Bug

I looked into this case in particular: 

- If the test environment's bitcoind has been running for a long time, bcoin's in memory wallet provided by the SDK will become unreliable and often display incorrect balances.


### Reproduction

-   Branch off `create-comit-app`'s `dev` branch and add a `wallet-test` project, next to `demos` and `examples`
-   Source code
```typescript
        // index.ts
        
        import { InMemoryBitcoinWallet } from "comit-sdk";
        import dotenv from "dotenv";
        import fs from "fs";
        import * as os from "os";
        import * as path from "path";
        
        (async function main() {
            loadEnvironment();
        
            const payerWallet = await createWallet(0);
            const receiverWallet = await createWallet(1);
            const sendAddress = await receiverWallet.getAddress();
        
            console.log("Payer: " + (await payerWallet.getBalance()));
            console.log("Receiver: " + (await receiverWallet.getBalance()));
        
            await payerWallet.sendToAddress(sendAddress, 10_000_000, "regtest");
        
            console.log("Payer: " + (await payerWallet.getBalance()));
            console.log("Receiver: " + (await receiverWallet.getBalance()));
        
            process.exit();
        })();
        
        async function createWallet(index: number): Promise<InMemoryBitcoinWallet> {
            const [wallet] = await Promise.all<InMemoryBitcoinWallet, void>([
                InMemoryBitcoinWallet.newInstance(
                    "regtest",
                    process.env.BITCOIN_P2P_URI!,
                    process.env[`BITCOIN_HD_KEY_${index}`]!
                ),
                new Promise(r => setTimeout(r, 1000)),
            ]);
        
            return wallet;
        }
        
        function loadEnvironment() {
            const envFilePath = path.join(os.homedir(), ".create-comit-app", "env");
        
            if (!fs.existsSync(envFilePath)) {
                console.log(
                    "Could not find file %s. Did you run `yarn start-env`?",
                    envFilePath
                );
                process.exit(1);
            }
        
            dotenv.config({ path: envFilePath });
        }
```

-   Execute main function, transferring 0.1 bitcoin from payer to receiver
-   Run `docker exec bitcoin bitcoin-cli -regtest generate 10000` in terminal. This is the equivalent of keeping the environment up for ~3 hours, since on environment start-up we instruct one "miner" to mine 1 block per second.
-   Executing the main function several times will show that the receiver's balance is inconsistent. Interestingly, the payer's balance remains correct throughout.


### Thoughts and questions

1.  Modifying the SDK's in-memory bcoin wallet to log certain events can show that bcoin receives blocks in chronological order. Since nothing is persisted between instantiations of the wallet, all blocks will need to be received every time the wallet is instantiated. Therefore, if a transaction has awarded some coins to a wallet, but it was included in a block way above the genesis block, the wallet will not be able to reflect this in its balance until that block has been seen by the wallet. 
    
    I was unsuccessful in managing to properly wait for bcoin to confirm that it was synced up with its one peer, `bitcoind`, but I think it can be done. I tried to wait for the `chain` to emit a `full` event, but kept encountering timeout errors. In any case, I can't see this solution scaling, given that the time the user will need to wait between restarts will grow linearly with the time since the test environment was started up.
2.  Is it right to mine 1 block per second on Bitcoin? I believe the purpose of this is to not have to wait for a few blocks to be mined to execute a swap. I think in the past we dealt with this by mining blocks on demand, but we moved away from that because it wasn't realistic. That may be a concern for testing, but does an SDK user care about that? Can bitcoin wallets even keep up with such a mining rate?
3.  Could this be solved by persisting the state of the wallet, like we do in the [testnet demo](https://github.com/comit-network/testnet-demo/)?
4.  Why don't we have similar problems with the Ethereum wallet if we also have a very fast miner?

---

### Conversation with Philipp

I presented my notes to @bonomat and we came to the conclusion that we would be happy to replace `bcoin` with `bitcoind`'s wallet as a solution to this problem.

Keeping an in-memory `bcoin` wallet and `bitcoind` in sync appears to not be trivial given the very fast mining rate. This appears to be the source of our problems. We expect that `bitcoind` and its wallet would remain in sync without trouble.

It is not considered good practice to have a wallet inside a node, and `bitcoind` is moving away from this by separating the wallet out of the node, but for the time being and considering that the wallet provided by the SDK is only for testing, we are okay with using this wallet. Once `bitcoind` extracts the wallet, we expect that it would be easy to still keep the wallet in sync with the node, given that the are developed by the same people.

In terms of implementation, @bonomat had a clear picture in his head, but I will leave out implementation details until we agree that this is the way forward.

Thoughts? @da-kami @thomaseizinger @D4nte

**Comment by thomaseizinger** [comment] 2020-04-06 02:10
I am okay with using bitcoind's wallet if we still initialize the wallet from the SDK, i.e. the SDK has power over the seed.

Within create-comit-app, we generate HD-keys for the individual wallets and fund them. At this stage, the bitcoind node does **not** know about the private keys. This should be kept as is IMO.
Instead, it should be the application/SDKs decision to take this HD key and initialize a wallet within bitcoind.

The reason why I think this is important is because I would assume that an application would want to be in control of the wallet seed and may want to use a single HD-key to derive the bitcoin and ethereum seed for example.
Using bitcoind's wallet is definitely feasible (also in production) but I would want our usage of it to be **explicit**.
This also makes sure that the application stays environment agnostic and doesn't assume that create-comit-app is present.

**Comment by bonomat** [comment] 2020-04-06 02:59
Thanks for writing this up with such detail. I think the summary @thomaseizinger indicates how this can/should be implemented and the reasoning nicely outlines why :)

**Comment by bonomat** [comment] 2020-04-09 11:48
Hi @luckysori, 

I learned a bit about extended private/public keys today :)

An extended key is just a base58 encoded serialization of a few pieces of data :

`[ magic ][ depth ][ parent fingerprint ][ key index ][ chain code ][ key ]` 

` magic `             = 04358394 (for testnet)
` depth `             = indicates how deep the key in a particular path is
` parent fingerprint` = the first 4 bytes of the parent's hash160
` key index`          = always 4 bytes , left padded with 0 indicates the, it's the index of the ` depth `
` chain code `        = hmac-sha512 of the root seed and then the right 256bits (checkout the stackoverflow link at the end)
` key `               = 32 bytes for the key (leftpadded to 33 bytes with 0 if priv key)
` XXXXXXXX `          = 4 bytes of something, TODO don't know what this is, maybe a checksum? 


Example: 

extended private key: 
`tprv8ZgxMBicQKsPexMYNfrPcqmezBejab45i7kVwx2innNM4EdGXa92Ga1T1SreoJviCKooHUJDPtWtXjGB3RLqf7dxSHeVKQbAJU18nYnHhV6`

```
bx base58-decode tprv8ZgxMBicQKsPexMYNfrPcqmezBejab45i7kVwx2innNM4EdGXa92Ga1T1SreoJviCKooHUJDPtWtXjGB3RLqf7dxSHeVKQbAJU18nYnHhV6
--> 04358394000000000000000000d1225dfddd3f84abc22e881bc97ac1e76b4cb37886cd6e5e3f44b912f54c93a00076bfe8f4ec99ad74f4d81e85382e427f9153343642df064d8913745a7e608d7925012d6d
```

| field  | value  |
|---|---|
|  magic |  04358394 |
|  depth |  00 |
|  parent | 00000000  |
|  key index |  00000000 |
|  chain code |  d1225dfddd3f84abc22e881bc97ac1e76b4cb37886cd6e5e3f44b912f54c93a0 |
|  key |  0076bfe8f4ec99ad74f4d81e85382e427f9153343642df064d8913745a7e608d79 |
|  XXXX | 25012d6d  |


The key is the interesting thing. 
We can generate the WIF from the key with: 
```
bx ec-to-wif -v 239 76bfe8f4ec99ad74f4d81e85382e427f9153343642df064d8913745a7e608d79
--> cRZY1UJMQ4v5z8eBwiFwKNx7EPEm3oyWBPvdiJVhpHpvdyXiJgWp
```

And then go ahead and import it into bitcoind. (That's what we did so far).

So far so good right? :)

The problem is, that when we import the WIF into bitcoin, we ignore the `chain code` part which is crucial for deriving keys. We only import the WIF (key in WIF format). 
In order to derive child keys we would need the `chain code` and `key` of the xprv and the index at which we want to derive the child (check the stackexchange link below). 

Because we only import the `key`, and not the `chain code`, bitcoind cannot derive the same private keys as we do in create-comit-app and hence it cannot find the money :)

Now, what I don't understand is how the bitcoind generates its xprv key when we import the WIF. imho they would need to be related somehow. I'd assume the key is the HMAC-SHA512 algorithm. 


~~~~
# Solution

The right way to import the xprv key is using `bitcoin-cli importmulti`

I couldn't get it working so far but I have the feeling I'm relatively close :) 

```bash
docker exec -it bad3f31a6ad1 bitcoin-cli --regtest createwallet wif

docker exec -it bad3f31a6ad1 bitcoin-cli --regtest -rpcwallet=wif importmulti '[{ "scriptPubKey": {"address":"2Mt5JdHbPPzbYShHSscm7VQZsuDTTmR7hVo"}, "desc" : "sh(wpkh(tprv8ZgxMBicQKsPedbF8qeGz31iUxqRVqih1y29YpC81KiUhSVXNcKKQ18op27kJU1PVbAghy4KJ2S5ESA4deZSA8d7LSvq7SgRYdBHSdx18Wg/0h/0h/*h))", "timestamp" : 0 , "range": 3 }]' '{ "rescan": true}'
```
returns true?! but not sure if it really worked :D 

```
docker exec -it bad3f31a6ad1 bitcoin-cli --regtest -rpcwallet=wif getbalance
```

It fails or has no effect for now but it could be that it's because we are using bitcoind-0.17. 
In 0.19. there seem to be a useful helper function available: https://bitcoincore.org/en/doc/0.19.0/rpc/util/getdescriptorinfo/

I'll give it a try tomorrow :) 



Link:
* http://bip32.org/
* https://bitcoin.stackexchange.com/questions/62533/key-derivation-in-hd-wallets-using-the-extended-private-key-vs-hardened-derivati

**Comment by thomaseizinger** [comment] 2020-04-09 22:28
What it is worth, to my understanding WIF is only for a single key and pretty much a legacy format. At least over in the rust-bitcoin repo, they talk about it as a legacy format.

**Comment by thomaseizinger** [comment] 2020-04-09 22:36
Found this in the 0.18.0 release notes: https://bitcoin.org/en/release/v0.18.0#updated-rpcs

> createwallet now has an optional blank argument that can be used to create a blank wallet. Blank wallets do not have any keys or HD seed. They cannot be opened in software older than 0.18. Once a blank wallet has a HD seed set (by using sethdseed) or private keys, scripts, addresses, and other watch only things have been imported, the wallet is no longer blank and can be opened in 0.17.x. Encrypting a blank wallet will also set a HD seed for it.

**Comment by thomaseizinger** [comment] 2020-04-09 22:37
From past experience, I would recommend to always update to the latest version of things first before going down debugging rabbit holes :)

**Comment by bonomat** [comment] 2020-04-09 23:25
> Found this in the 0.18.0 release notes: [bitcoin.org/en/release/v0.18.0#updated-rpcs](https://bitcoin.org/en/release/v0.18.0#updated-rpcs)
> 
> > createwallet now has an optional blank argument that can be used to create a blank wallet. Blank wallets do not have any keys or HD seed. They cannot be opened in software older than 0.18. Once a blank wallet has a HD seed set (by using sethdseed) or private keys, scripts, addresses, and other watch only things have been imported, the wallet is no longer blank and can be opened in 0.17.x. Encrypting a blank wallet will also set a HD seed for it.

Unfortunately this does not help us with our current approach. If we keep generating an extended public key and derive an address from this then we can't import the xprv into bitcoind with `sethdseed`. See the description above of the missing `chain_code` which you can't import. 
Afaik `importmulti` allows us to do so though. 

Another solution (and I think that's what Lucas is going for) is to 
1) generate a single private key in create-comit-app, 
2) create an address from this, 
3) fund this address 
4) and then import this single private key into a wallet of your choice.

**Comment by bonomat** [comment] 2020-04-13 00:57
found the solution:

start bitcoin:  `bitcoind --regtest`
```

bitcoin-cli getnewaddress 
--> 2N6HMhg43ufw5xZxB1WGCkfbBnmx63DcqYo
bitcoin-cli generatetoaddress 101 2N6HMhg43ufw5xZxB1WGCkfbBnmx63DcqYo
bitcoin-cli sendtoaddress bcrt1qlpc77eum9snqmu05j9rna949u2d3nrg4we0233 10

bitcoin-cli createwallet xpriv

bitcoin-cli --rpcwallet=xpriv getbalance
--> 0

bitcoin-cli getdescriptorinfo "wpkh(tprv8ZgxMBicQKsPei4Fj88YUeDtww6Dm845GjkaBuG7Eupeoeg3uqLyPACmcWkTgTAarmtABH86QWB9bFdMFyH1WTuuYphzUcPF8r9LDSi1ucG/0h/0h/*h)" | jq .checksum
--> lhllkea3

bitcoin-cli --rpcwallet=xpriv importmulti '[{ "desc" : "wpkh(tprv8ZgxMBicQKsPei4Fj88YUeDtww6Dm845GjkaBuG7Eupeoeg3uqLyPACmcWkTgTAarmtABH86QWB9bFdMFyH1WTuuYphzUcPF8r9LDSi1ucG/0h/0h/*h)#lhllkea3", "timestamp" : 0 , "range": 3 }]' '{ "rescan": true}'

bitcoin-cli --rpcwallet=xpriv getbalance
--> 10

```

**Comment by thomaseizinger** [comment] 2020-04-14 00:58
> Note: this descriptor is not compatible with what we have in create-comit-app by default (the derivation path is different). The one used above is the one used in bitcoind.

Shouldn't we be able to specify whatever derivation path we want here?

I don't mind any of these solutions :)
What I care about is that we don't completely roll our own thing. If possible, I would like us to follow some kind of standard of how create-comit-app distributes money to the app without the app having to cater specifically for create-comit-app.

A single private key sort of works but is also kind of awkward: Why would an app make use of the functionality of importing a single key?

**Closed** 2020-04-20 00:43 UTC
Labels: 🐛 bug, 🦄 10/50/99%

**Comment by yosriady** [comment] 2020-04-20 01:34
If we want to extract wallets out, I think we should look into the `Provider` standard similar to https://github.com/liquality/chainabstractionlayer

**Comment by thomaseizinger** [comment] 2020-04-20 03:56
Good reference thanks! :)
I'd hope we can delay this kind of micro-package stuff for as long as possible to avoid the giant overhead that comes with it!
